# Generated by Django 3.1.6 on 2021-08-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMIList', '0013_auto_20210823_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='sex',
            field=models.TextField(default='---', max_length=20),
        ),
    ]
